<?php
session_start();
require 'db_connect.php';

if (!isset($_SESSION['username'])) {
    header("Location: login.php");
    exit();
}

// Get filter parameters from POST
$reportType = $_POST['report_type'] ?? 'both';
$startDate = $_POST['start_date'] ?? '';
$endDate = $_POST['end_date'] ?? '';
$inventoryStatus = $_POST['inventory_status'] ?? 'all';
$transactionStatus = $_POST['transaction_status'] ?? 'all';

// Build inventory query
$inventoryWhere = [];
if ($inventoryStatus !== 'all') {
    $inventoryWhere[] = "item_availability = '" . $conn->real_escape_string($inventoryStatus) . "'";
}
$inventorySql = "SELECT * FROM inventory";
if (!empty($inventoryWhere)) {
    $inventorySql .= " WHERE " . implode(" AND ", $inventoryWhere);
}

// Build transactions query
$transactionWhere = [];
if ($transactionStatus !== 'all') {
    $transactionWhere[] = "status = '" . $conn->real_escape_string($transactionStatus) . "'";
}
if (!empty($startDate)) {
    $transactionWhere[] = "transaction_date >= '" . $conn->real_escape_string($startDate) . "'";
}
if (!empty($endDate)) {
    $transactionWhere[] = "transaction_date <= '" . $conn->real_escape_string($endDate) . " 23:59:59'";
}

$transactionSql = "SELECT * FROM transactions";
if (!empty($transactionWhere)) {
    $transactionSql .= " WHERE " . implode(" AND ", $transactionWhere);
}

// Execute queries based on selected report type
$inventoryData = [];
$transactionData = [];

if ($reportType === 'inventory' || $reportType === 'both') {
    $inventoryResult = $conn->query($inventorySql);
    $inventoryData = $inventoryResult->fetch_all(MYSQLI_ASSOC);
}

if ($reportType === 'transactions' || $reportType === 'both') {
    $transactionResult = $conn->query($transactionSql);
    $transactionData = $transactionResult->fetch_all(MYSQLI_ASSOC);
}

$conn->close();

// Set headers for Excel download
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="IMS_Report_' . date('Ymd_His') . '.xls"');

// Create Excel content
echo '<html>';
echo '<head>';
echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
echo '<style>';
echo 'td { padding: 5px; border: 1px solid #ddd; }';
echo 'th { background-color: #f2f2f2; padding: 5px; border: 1px solid #ddd; }';
echo '</style>';
echo '</head>';
echo '<body>';

echo '<h2>Inventory Management System Report</h2>';
echo '<p><strong>Generated on:</strong> ' . date('Y-m-d H:i:s') . '</p>';
echo '<p><strong>Generated by:</strong> ' . $_SESSION['username'] . '</p>';
echo '<p><strong>Report Type:</strong> ' . ucfirst($reportType) . ' report</p>';
if ($reportType !== 'inventory') {
    echo '<p><strong>Date Range:</strong> ' . (!empty($startDate) ? $startDate : 'Start') . ' to ' . (!empty($endDate) ? $endDate : 'End') . '</p>';
}

if (empty($inventoryData) && empty($transactionData)) {
    echo '<p>No data available for the selected filters.</p>';
} else {
    // Inventory Report
    if (($reportType === 'inventory' || $reportType === 'both') && !empty($inventoryData)) {
        echo '<h3>Inventory Report</h3>';
        echo '<table>';
        echo '<tr>';
        echo '<th>ID</th>';
        echo '<th>Item Name</th>';
        echo '<th>Quantity</th>';
        echo '<th>Availability</th>';
        echo '<th>Last Updated</th>';
        echo '</tr>';
        
        foreach ($inventoryData as $item) {
            echo '<tr>';
            echo '<td>' . $item['id'] . '</td>';
            echo '<td>' . htmlspecialchars($item['item_name']) . '</td>';
            echo '<td>' . $item['item_quantity'] . '</td>';
            echo '<td>' . ucfirst($item['item_availability']) . '</td>';
            echo '<td>' . (!empty($item['last_updated']) ? date('Y-m-d H:i', strtotime($item['last_updated'])) : 'N/A') . '</td>';
            echo '</tr>';
        }
        
        echo '<tr>';
        echo '<td colspan="5" style="text-align: right;"><strong>Total Items:</strong> ' . count($inventoryData) . '</td>';
        echo '</tr>';
        echo '</table>';
        echo '<br><br>';
    }

    // Transactions Report
    if (($reportType === 'transactions' || $reportType === 'both') && !empty($transactionData)) {
        echo '<h3>Transactions Report</h3>';
        echo '<table>';
        echo '<tr>';
        echo '<th>ID</th>';
        echo '<th>Item ID</th>';
        echo '<th>Item Name</th>';
        echo '<th>Student ID</th>';
        echo '<th>Student Name</th>';
        echo '<th>Type</th>';
        echo '<th>Date</th>';
        echo '<th>Status</th>';
        echo '<th>Verified By</th>';
        echo '</tr>';
        
        foreach ($transactionData as $transaction) {
            echo '<tr>';
            echo '<td>' . $transaction['id'] . '</td>';
            echo '<td>' . $transaction['item_id'] . '</td>';
            echo '<td>' . htmlspecialchars($transaction['item_name'] ?? 'N/A') . '</td>';
            echo '<td>' . $transaction['student_id'] . '</td>';
            echo '<td>' . htmlspecialchars($transaction['student_name']) . '</td>';
            echo '<td>' . ucfirst($transaction['transaction_type']) . '</td>';
            echo '<td>' . date('Y-m-d H:i', strtotime($transaction['transaction_date'])) . '</td>';
            echo '<td>' . ucfirst($transaction['status']) . '</td>';
            echo '<td>' . htmlspecialchars($transaction['verified_by']) . '</td>';
            echo '</tr>';
        }
        
        echo '<tr>';
        echo '<td colspan="9" style="text-align: right;"><strong>Total Transactions:</strong> ' . count($transactionData) . '</td>';
        echo '</tr>';
        echo '</table>';
    }
}

echo '</body>';
echo '</html>';
?>